from __future__ import annotations

import importlib.util
from pathlib import Path


MODULE_PATH = Path(__file__).parents[1] / "analysis" / "step6b_rearm_repeatability.py"
SPEC = importlib.util.spec_from_file_location("step6b_rearm", MODULE_PATH)
assert SPEC and SPEC.loader
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


PASS = """\
S6B_SOURCE_WRITE BOARD=MASTER ROLE=MASTER INDEX=68 VALUE=0 OK=1
S6B_SOURCE_WRITE BOARD=SLAVE ROLE=SLAVE INDEX=68 VALUE=0 OK=1
S6B_SOURCE_WRITE BOARD=MASTER ROLE=MASTER INDEX=67 VALUE=00000000000000000D7A OK=1
S6B_SOURCE_WRITE BOARD=SLAVE ROLE=SLAVE INDEX=67 VALUE=00000000000000000D7A OK=1
S6B_SOURCE_WRITE BOARD=MASTER ROLE=MASTER INDEX=68 VALUE=1 OK=1
S6B_SOURCE_WRITE BOARD=SLAVE ROLE=SLAVE INDEX=68 VALUE=1 OK=1
S6B_REARM_RESULT=PASS_DIGITAL_SCHEDULED_DUAL_BOARD_TRIGGER_REARM_REPEATABILITY PHASE=capture TRIAL=x PRE_GATE_PAIRS=3 PRE_COMMON_TAI_COUNT=2 POST_DEARM_GATE_PAIRS=2 POST_DEARM_COMMON_TAI_COUNT=2 COHERENCE_VIOLATION=0 T0=3430 NEW_TARGET_TAI=3450 TARGET_CYCLES=62500000 PRE_GATE_RESULT=PASS INITIAL_RESULT=PASS DEARM_RESULT=PASS POST_DEARM_GATE_RESULT=PASS TARGET_RESULT=PASS ARM_RESULT=PASS CAPTURE_SAMPLES=20 POST_FIRE_SAMPLES=3 ARM0_WRITE_MASTER=1 ARM0_WRITE_SLAVE=1 TARGET_WRITE_MASTER=1 TARGET_WRITE_SLAVE=1 ARM1_WRITE_MASTER=1 ARM1_WRITE_SLAVE=1 MASTER_FIRE_COUNT=2 SLAVE_FIRE_COUNT=2 MASTER_ACTUAL_TAI=3450 SLAVE_ACTUAL_TAI=3450 MASTER_ACTUAL_CYCLES=62500000 SLAVE_ACTUAL_CYCLES=62500000 SECOND_TRIGGER_DELTA_TICKS=0 SECOND_TRIGGER_DELTA_NS=0
"""


def test_formal_rearm_pass_requires_six_writes_in_order() -> None:
    result = MODULE.analyze_text(PASS)
    assert result["classification"] == (
        "PASS_DIGITAL_SCHEDULED_DUAL_BOARD_TRIGGER_REARM_REPEATABILITY"
    )
    assert result["verdict"] == "PASS"
    assert result["source_sequence_ok"] is True
    assert result["write_count"] == 6
    assert result["second_trigger_delta_ticks"] == 0


def test_reversed_write_order_is_not_formal_pass() -> None:
    bad = PASS.replace(
        "S6B_SOURCE_WRITE BOARD=MASTER ROLE=MASTER INDEX=68 VALUE=0 OK=1\n"
        "S6B_SOURCE_WRITE BOARD=SLAVE ROLE=SLAVE INDEX=68 VALUE=0 OK=1",
        "S6B_SOURCE_WRITE BOARD=SLAVE ROLE=SLAVE INDEX=68 VALUE=0 OK=1\n"
        "S6B_SOURCE_WRITE BOARD=MASTER ROLE=MASTER INDEX=68 VALUE=0 OK=1",
    )
    result = MODULE.analyze_text(bad)
    assert result["verdict"] == "INCONCLUSIVE"
    assert result["source_sequence_ok"] is False


def test_functional_fail_is_preserved() -> None:
    result = MODULE.analyze_text(
        PASS.replace(
            "PASS_DIGITAL_SCHEDULED_DUAL_BOARD_TRIGGER_REARM_REPEATABILITY",
            "FAIL_SECOND_TRIGGER_TIMESTAMP_MISMATCH",
        ).replace("SECOND_TRIGGER_DELTA_TICKS=0", "SECOND_TRIGGER_DELTA_TICKS=1")
    )
    assert result["classification"] == "FAIL_SECOND_TRIGGER_TIMESTAMP_MISMATCH"
    assert result["verdict"] == "FAIL"
